# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditConfigWindow(object):
    def setupUi(self, EditConfigWindow):
        EditConfigWindow.setObjectName("EditConfigWindow")
        EditConfigWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(EditConfigWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(230, 10, 341, 51))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.HeaderLabel.sizePolicy().hasHeightForWidth())
        self.HeaderLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.HeaderLabel.setFont(font)
        self.HeaderLabel.setScaledContents(False)
        self.HeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.DisplayListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.DisplayListWidget.setGeometry(QtCore.QRect(80, 60, 641, 261))
        self.DisplayListWidget.setObjectName("DisplayListWidget")
        self.SererIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.SererIPLabel.setGeometry(QtCore.QRect(130, 370, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SererIPLabel.setFont(font)
        self.SererIPLabel.setObjectName("SererIPLabel")
        self.ServerPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.ServerPortLabel.setGeometry(QtCore.QRect(120, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ServerPortLabel.setFont(font)
        self.ServerPortLabel.setObjectName("ServerPortLabel")
        self.AutoLoadButton = QtWidgets.QRadioButton(self.centralwidget)
        self.AutoLoadButton.setGeometry(QtCore.QRect(140, 450, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AutoLoadButton.setFont(font)
        self.AutoLoadButton.setObjectName("AutoLoadButton")
        self.ServerIPLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ServerIPLineEdit.setGeometry(QtCore.QRect(210, 370, 181, 31))
        self.ServerIPLineEdit.setObjectName("ServerIPLineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 410, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.EditExistinglabel = QtWidgets.QLabel(self.centralwidget)
        self.EditExistinglabel.setGeometry(QtCore.QRect(130, 330, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EditExistinglabel.setFont(font)
        self.EditExistinglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EditExistinglabel.setObjectName("EditExistinglabel")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setEnabled(False)
        self.SaveButton.setGeometry(QtCore.QRect(430, 370, 121, 41))
        self.SaveButton.setObjectName("SaveButton")
        self.RemoveButton = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveButton.setEnabled(False)
        self.RemoveButton.setGeometry(QtCore.QRect(580, 370, 121, 41))
        self.RemoveButton.setObjectName("RemoveButton")
        self.IndexLabel = QtWidgets.QLabel(self.centralwidget)
        self.IndexLabel.setGeometry(QtCore.QRect(570, 420, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IndexLabel.setFont(font)
        self.IndexLabel.setObjectName("IndexLabel")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(330, 480, 121, 41))
        self.BackButton.setObjectName("BackButton")
        self.AddNewConnectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddNewConnectionButton.setEnabled(False)
        self.AddNewConnectionButton.setGeometry(
            QtCore.QRect(430, 420, 121, 41))
        self.AddNewConnectionButton.setObjectName("AddNewConnectionButton")
        EditConfigWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EditConfigWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        EditConfigWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EditConfigWindow)
        self.statusbar.setObjectName("statusbar")
        EditConfigWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EditConfigWindow)
        QtCore.QMetaObject.connectSlotsByName(EditConfigWindow)

    def retranslateUi(self, EditConfigWindow):
        _translate = QtCore.QCoreApplication.translate
        EditConfigWindow.setWindowTitle(_translate(
            "EditConfigWindow", "Edit Config File"))
        self.HeaderLabel.setText(_translate(
            "EditConfigWindow", "Config File Modify"))
        self.SererIPLabel.setText(_translate(
            "EditConfigWindow", "Server IP: "))
        self.ServerPortLabel.setText(_translate(
            "EditConfigWindow", "Server Port:"))
        self.AutoLoadButton.setText(_translate(
            "EditConfigWindow", "Auto Load Info"))
        self.EditExistinglabel.setText(_translate(
            "EditConfigWindow", "Edit Existing Connection or Add a New Connection"))
        self.SaveButton.setText(_translate("EditConfigWindow", "Save Edits"))
        self.RemoveButton.setText(_translate("EditConfigWindow", "Remove"))
        self.IndexLabel.setText(_translate(
            "EditConfigWindow", "Current Index:"))
        self.BackButton.setText(_translate("EditConfigWindow", "Back"))
        self.AddNewConnectionButton.setText(
            _translate("EditConfigWindow", "Add New"))
