# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileSharingHomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(750, 400)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MoreInfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.MoreInfoButton.setGeometry(QtCore.QRect(120, 230, 121, 41))
        self.MoreInfoButton.setObjectName("MoreInfoButton")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(320, 230, 121, 41))
        self.ConnectButton.setObjectName("ConnectButton")
        self.iniConfigButton = QtWidgets.QPushButton(self.centralwidget)
        self.iniConfigButton.setGeometry(QtCore.QRect(510, 230, 121, 41))
        self.iniConfigButton.setObjectName("iniConfigButton")
        self.QuitButton = QtWidgets.QPushButton(self.centralwidget)
        self.QuitButton.setGeometry(QtCore.QRect(320, 300, 121, 41))
        self.QuitButton.setObjectName("QuitButton")
        self.WelcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.WelcomeLabel.setGeometry(QtCore.QRect(130, 10, 501, 201))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.WelcomeLabel.setFont(font)
        self.WelcomeLabel.setWordWrap(True)
        self.WelcomeLabel.setObjectName("WelcomeLabel")
        StartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menubar.setObjectName("menubar")
        StartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate(
            "StartWindow", "Filsharing Client V2.0.1"))
        self.MoreInfoButton.setText(_translate("StartWindow", "More Info"))
        self.ConnectButton.setText(_translate("StartWindow", "Connect"))
        self.iniConfigButton.setText(_translate("StartWindow", "ini Config"))
        self.QuitButton.setText(_translate("StartWindow", "Quit"))
        self.WelcomeLabel.setText(_translate("StartWindow", "Welcome to my filesharing application! I have added functionality to connect to a locally hosted FTP server that stores files and allows for Syning between devices on the same network. On this page you can view additional information about this project including usage information from the ReadMe file. There also is a Connect button to connect to a locally hosted FTP server and once connected other functions will become available. Lastly there is an ini Config button allowing runtime modification of the configuration file. If you encounter any issues with the script please refer to the readme.txt file for help."))
