# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\1shab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\QtDesigner\Connect.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectWindow(object):
    def setupUi(self, ConnectWindow):
        ConnectWindow.setObjectName("ConnectWindow")
        ConnectWindow.resize(800, 294)
        self.centralwidget = QtWidgets.QWidget(ConnectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ServerIPLabel = QtWidgets.QLabel(self.centralwidget)
        self.ServerIPLabel.setGeometry(QtCore.QRect(130, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ServerIPLabel.setFont(font)
        self.ServerIPLabel.setObjectName("ServerIPLabel")
        self.ServerPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.ServerPortLabel.setGeometry(QtCore.QRect(420, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ServerPortLabel.setFont(font)
        self.ServerPortLabel.setObjectName("ServerPortLabel")
        self.ServerIPLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ServerIPLineEdit.setGeometry(QtCore.QRect(210, 60, 191, 31))
        self.ServerIPLineEdit.setObjectName("ServerIPLineEdit")
        self.ServerPortLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ServerPortLineEdit.setGeometry(QtCore.QRect(510, 60, 191, 31))
        self.ServerPortLineEdit.setObjectName("ServerPortLineEdit")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(130, -1, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.HeaderLabel.setFont(font)
        self.HeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameLineEdit.setGeometry(QtCore.QRect(210, 110, 191, 31))
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(510, 110, 191, 31))
        self.PasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(200, 200, 121, 41))
        self.ConnectButton.setObjectName("ConnectButton")
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(520, 200, 121, 41))
        self.ClearButton.setObjectName("ClearButton")
        self.BackPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackPushButton.setGeometry(QtCore.QRect(360, 200, 121, 41))
        self.BackPushButton.setObjectName("BackPushButton")
        self.SavedConnectionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SavedConnectionComboBox.setGeometry(QtCore.QRect(290, 160, 271, 22))
        self.SavedConnectionComboBox.setCurrentText("")
        self.SavedConnectionComboBox.setObjectName("SavedConnectionComboBox")
        ConnectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConnectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ConnectWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConnectWindow)
        self.statusbar.setObjectName("statusbar")
        ConnectWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConnectWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectWindow)

    def retranslateUi(self, ConnectWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectWindow.setWindowTitle(_translate("ConnectWindow", "Connect to Server"))
        self.ServerIPLabel.setText(_translate("ConnectWindow", "Server IP:"))
        self.ServerPortLabel.setText(_translate("ConnectWindow", "Server Port:"))
        self.HeaderLabel.setText(_translate("ConnectWindow", "Connect to Server"))
        self.label.setText(_translate("ConnectWindow", "Username:"))
        self.label_2.setText(_translate("ConnectWindow", "Password:"))
        self.ConnectButton.setText(_translate("ConnectWindow", "Connect"))
        self.ClearButton.setText(_translate("ConnectWindow", "Clear"))
        self.BackPushButton.setText(_translate("ConnectWindow", "Back"))
