# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\1shab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\QtDesigner\Function.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FunctionWIndow(object):
    def setupUi(self, FunctionWIndow):
        FunctionWIndow.setObjectName("FunctionWIndow")
        FunctionWIndow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(FunctionWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.UploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.UploadButton.setGeometry(QtCore.QRect(170, 390, 121, 41))
        self.UploadButton.setObjectName("UploadButton")
        self.DownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadButton.setGeometry(QtCore.QRect(170, 460, 121, 41))
        self.DownloadButton.setObjectName("DownloadButton")
        self.MkdirButton = QtWidgets.QPushButton(self.centralwidget)
        self.MkdirButton.setGeometry(QtCore.QRect(530, 390, 121, 41))
        self.MkdirButton.setObjectName("MkdirButton")
        self.RmdirButton = QtWidgets.QPushButton(self.centralwidget)
        self.RmdirButton.setGeometry(QtCore.QRect(530, 460, 121, 41))
        self.RmdirButton.setObjectName("RmdirButton")
        self.RenameButton = QtWidgets.QPushButton(self.centralwidget)
        self.RenameButton.setGeometry(QtCore.QRect(350, 390, 121, 41))
        self.RenameButton.setObjectName("RenameButton")
        self.DisconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.DisconnectButton.setGeometry(QtCore.QRect(350, 460, 121, 41))
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.HeaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.HeaderLabel.setGeometry(QtCore.QRect(100, 0, 611, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.HeaderLabel.setFont(font)
        self.HeaderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HeaderLabel.setObjectName("HeaderLabel")
        self.FilesListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.FilesListWidget.setGeometry(QtCore.QRect(100, 50, 621, 331))
        self.FilesListWidget.setObjectName("FilesListWidget")
        FunctionWIndow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FunctionWIndow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        FunctionWIndow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FunctionWIndow)
        self.statusbar.setObjectName("statusbar")
        FunctionWIndow.setStatusBar(self.statusbar)

        self.retranslateUi(FunctionWIndow)
        QtCore.QMetaObject.connectSlotsByName(FunctionWIndow)

    def retranslateUi(self, FunctionWIndow):
        _translate = QtCore.QCoreApplication.translate
        FunctionWIndow.setWindowTitle(_translate("FunctionWIndow", "Functions"))
        self.UploadButton.setText(_translate("FunctionWIndow", "Upload"))
        self.DownloadButton.setText(_translate("FunctionWIndow", "Download"))
        self.MkdirButton.setText(_translate("FunctionWIndow", "Add a Directory"))
        self.RmdirButton.setText(_translate("FunctionWIndow", "Remove a Directory"))
        self.RenameButton.setText(_translate("FunctionWIndow", "Rename"))
        self.DisconnectButton.setText(_translate("FunctionWIndow", "Disconnect"))
        self.HeaderLabel.setText(_translate("FunctionWIndow", "Functions"))
